"use client";

import React from "react";
import LinkInnovationsNavbar from "@/components/LinkInnovationsNavbar";
import { Footer } from "@/components/Footer";
import { motion } from "motion/react";
import { CheckCircle, Code, Smartphone, Zap, BarChart3, GitBranch, ArrowRight, Star, Award, Mail, Phone, MapPin, Send, Shield } from "lucide-react";

export default function AutomationTestingPage() {
  return (
    <div className="min-h-screen bg-black">
      <LinkInnovationsNavbar />
      <section className="relative bg-black text-white py-20 md:py-32 overflow-hidden">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <motion.div initial={{ opacity: 0, y: 50 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8 }} className="text-center lg:text-left">
              <div className="inline-block mb-6"><span className="px-4 py-2 rounded-full bg-[#7877c6]/10 text-[#7877c6] text-sm font-semibold uppercase tracking-wider font-['Inter']">AUTOMATION TESTING</span></div>
              <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold leading-tight mb-6 text-transparent bg-clip-text bg-gradient-to-r from-[#7877c6] to-white font-['Orbitron']">Automation Testing — Continuous Quality at Speed</h1>
              <p className="text-xl text-gray-300 mb-8 font-['Inter']">Integrate functional, API, and performance testing into your CI/CD pipeline.</p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center lg:justify-start">
                <motion.a href="/contact" className="inline-flex items-center justify-center px-8 py-3 text-white bg-gradient-to-r from-[#7877c6] to-[#a78bfa] hover:from-[#a78bfa] hover:to-[#7877c6] transition-all duration-300 rounded-md min-h-[44px] font-['Inter']" whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>Request assessment</motion.a>
                <motion.a href="#capabilities" className="inline-flex items-center justify-center px-8 py-3 border border-gray-600 text-gray-300 bg-transparent hover:bg-gray-800 transition-all duration-300 rounded-md min-h-[44px] font-['Inter']" whileHover={{ scale: 1.05 }} whileTap={{ scale: 0.95 }}>See services</motion.a>
              </div>
            </motion.div>
            <motion.div initial={{ opacity: 0, x: 50 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.8, delay: 0.2 }} className="mt-12 lg:mt-0">
              <div className="relative"><img src="/herosectionimages/cloud.webp" alt="Testing" className="w-full h-auto max-w-lg rounded-lg shadow-2xl" /><div className="absolute inset-0 rounded-lg bg-gradient-to-r from-[#7877c6]/20 to-[#a78bfa]/20 blur-xl -z-10"></div></div>
            </motion.div>
          </div>
        </div>
        <div className="absolute inset-0 bg-gradient-to-br from-[#7877c6]/10 via-transparent to-[#a78bfa]/10"></div>
        <div className="absolute top-20 left-10 w-72 h-72 bg-[#7877c6]/5 rounded-full blur-3xl"></div>
        <div className="absolute bottom-20 right-10 w-96 h-96 bg-[#a78bfa]/5 rounded-full blur-3xl"></div>
      </section>
      <section className="py-12 bg-gray-900/50 border-y border-gray-800">
        <div className="container mx-auto px-6 lg:px-8">
          <p className="text-center text-sm text-gray-400 mb-8 font-['Inter']">Testing tools we use</p>
          <div className="grid grid-cols-3 md:grid-cols-6 gap-8 items-center justify-items-center">{["Cypress", "Playwright", "Selenium", "Jest", "k6", "Postman"].map((name, i) => (<div key={i} className="text-gray-400 font-semibold font-['Inter'] opacity-50 hover:opacity-100 transition-opacity">{name}</div>))}</div>
        </div>
      </section>
      <section id="capabilities" className="py-16 lg:py-24 bg-black">
        <div className="container mx-auto px-6 lg:px-8">
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center mb-16"><h2 className="text-4xl lg:text-5xl font-bold text-white mb-4 font-['Orbitron']">Complete testing coverage</h2></motion.div>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {[{ icon: <Code className="w-8 h-8 text-[#7877c6]" />, title: "E2E Testing", description: "Cypress, Playwright" }, { icon: <GitBranch className="w-8 h-8 text-[#7877c6]" />, title: "API Testing", description: "REST & GraphQL" }, { icon: <Smartphone className="w-8 h-8 text-[#7877c6]" />, title: "Mobile Testing", description: "Appium & Detox" }, { icon: <Zap className="w-8 h-8 text-[#7877c6]" />, title: "Performance", description: "Load testing" }].map((item, i) => (<motion.div key={i} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.1 }} className="text-center group"><div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-br from-[#7877c6]/20 to-[#a78bfa]/20 mb-6 group-hover:from-[#7877c6]/30 group-hover:to-[#a78bfa]/30 transition-all">{item.icon}</div><h3 className="text-xl font-bold text-white mb-3 font-['Exo_2']">{item.title}</h3><p className="text-gray-400 font-['Inter']">{item.description}</p></motion.div>))}
          </div>
        </div>
      </section>
      <section className="py-16 lg:py-24 bg-gray-900/50">
        <div className="container mx-auto px-6 lg:px-8 space-y-24">
          {[{ badge: "FUNCTIONAL", title: "Automated UI testing", description: "E2E test suites that catch regressions.", image: "/herosectionimages/Digital Technology.webp", position: "right" }, { badge: "CI/CD", title: "Shift-left testing", description: "Tests in your pipeline for fast feedback.", image: "/herosectionimages/cloud.webp", position: "left" }, { badge: "PERFORMANCE", title: "Identify bottlenecks", description: "Load testing with k6, JMeter, Gatling.", image: "/herosectionimages/Scalable Cloud and Application.webp", position: "right" }, { badge: "API", title: "API test automation", description: "REST and GraphQL validation.", image: "/herosectionimages/Digital Partner.webp", position: "left" }, { badge: "MOBILE", title: "Mobile test automation", description: "Cross-device testing with Appium.", image: "/Service Cards images/Engineering and Manufacturing.webp", position: "right" }, { badge: "INTEGRATION", title: "Integration testing", description: "Test complex system interactions.", image: "/Service Cards images/Cloud and Application Service.webp", position: "left" }].map((s, idx) => (<div key={idx} className="grid lg:grid-cols-2 gap-12 items-center"><motion.div initial={{ opacity: 0, x: s.position === "right" ? -30 : 30 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} className={s.position === "left" ? "lg:order-2" : ""}><div className="inline-block mb-4"><span className="text-sm font-semibold text-[#7877c6] uppercase tracking-wider font-['Inter']">{s.badge}</span></div><h3 className="text-4xl font-bold text-white mb-6 font-['Orbitron']">{s.title}</h3><p className="text-lg text-gray-400 mb-8 font-['Inter']">{s.description}</p><a href="#" className="inline-flex items-center gap-2 text-[#7877c6] font-semibold hover:gap-4 transition-all font-['Inter']">Learn more <ArrowRight className="w-5 h-5" /></a></motion.div><motion.div initial={{ opacity: 0, x: s.position === "right" ? 30 : -30 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} className={s.position === "left" ? "lg:order-1" : ""}><div className="relative aspect-[4/3] rounded-2xl overflow-hidden bg-gray-800"><img src={s.image} alt={s.title} className="w-full h-full object-cover" loading="lazy" /></div></motion.div></div>))}
        </div>
      </section>
      <section className="py-24 bg-black"><div className="container mx-auto px-6 lg:px-8"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center mb-16"><h2 className="text-4xl lg:text-5xl font-bold text-white mb-4 font-['Orbitron']">Client success</h2></motion.div><div className="grid md:grid-cols-3 gap-8">{[{ quote: "Automation cut regression from 48h to 3h!", author: "Jessica Morgan", role: "QA Lead", company: "SaaS Y", rating: 5 }, { quote: "Performance testing saved us disasters.", author: "Kevin Zhang", role: "Eng Manager", company: "E-Commerce", rating: 5 }, { quote: "Flaky tests are history. Rock solid!", author: "Sophia Williams", role: "VP Quality", company: "FinTech", rating: 5 }].map((t, i) => (<motion.div key={i} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="p-8 rounded-2xl bg-gray-900/50 border border-gray-800 hover:border-[#7877c6]/30 hover:shadow-lg hover:shadow-[#7877c6]/10 transition-all"><div className="flex gap-1 mb-4">{Array.from({ length: 5 }).map((_, j) => (<Star key={j} className={`w-5 h-5 ${j < t.rating ? "fill-yellow-400 text-yellow-400" : "text-gray-600"}`} />))}</div><p className="text-gray-300 mb-6 font-['Inter']">"{t.quote}"</p><div className="flex items-center gap-3 pt-6 border-t border-gray-700"><div className="w-12 h-12 rounded-full bg-gradient-to-br from-[#7877c6]/20 to-[#a78bfa]/20 flex items-center justify-center font-bold text-[#7877c6]">{t.author.charAt(0)}</div><div><div className="font-semibold text-white font-['Inter']">{t.author}</div><div className="text-sm text-gray-400 font-['Inter']">{t.role}, {t.company}</div></div></div></motion.div>))}</div></div></section>
      <section className="py-24 bg-gray-900/50"><div className="container mx-auto px-6 lg:px-8"><motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center mb-16"><h2 className="text-4xl lg:text-5xl font-bold text-white mb-4 font-['Orbitron']">Our team</h2></motion.div><div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">{[{ name: "QA Lead", role: "Test Architect", icon: Shield }, { name: "Automation Engineer", role: "Cypress Expert", icon: Code }, { name: "Performance Lead", role: "Load Testing", icon: Zap }, { name: "Mobile QA", role: "Appium Expert", icon: Smartphone }, { name: "API Tester", role: "REST/GraphQL", icon: GitBranch }, { name: "CI/CD Engineer", role: "Pipeline Testing", icon: Zap }, { name: "Security Tester", role: "Pen Testing", icon: Shield }, { name: "QA Manager", role: "Strategy Lead", icon: BarChart3 }].map((m, i) => (<motion.div key={i} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center"><div className="w-full aspect-square rounded-2xl bg-gradient-to-br from-[#7877c6]/10 to-[#a78bfa]/10 flex items-center justify-center border border-gray-800 mb-6">{React.createElement(m.icon, { className: "w-16 h-16 text-[#7877c6]" })}</div><h3 className="text-lg font-bold text-white mb-1 font-['Exo_2']">{m.name}</h3><p className="text-gray-400 font-['Inter']">{m.role}</p></motion.div>))}</div><motion.div initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} className="mt-16 text-center"><a href="/careers" className="inline-flex items-center gap-2 text-[#7877c6] font-semibold hover:gap-4 transition-all font-['Inter']">We're hiring <ArrowRight className="w-5 h-5" /></a></motion.div></div></section>
      <section className="py-24 bg-black"><div className="container mx-auto px-6 lg:px-8"><h2 className="text-4xl font-bold text-white mb-16 font-['Orbitron']">Our testing journey</h2><div className="space-y-16 max-w-4xl">{[{ year: "2018", title: "Testing start", description: "Manual to automation", tags: ["Selenium", "Manual"] }, { year: "2020", title: "CI/CD", description: "Pipeline integration", tags: ["Jenkins", "CI/CD"] }, { year: "2022", title: "Modern tools", description: "Cypress and Playwright", tags: ["Cypress", "Modern"] }, { year: "2024", title: "Excellence", description: "Leading QA automation", tags: ["Innovation", "Quality"] }].map((e, i) => (<motion.div key={i} initial={{ opacity: 0, x: -30 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true }} className="grid md:grid-cols-[200px_1fr_300px] gap-8"><div className="text-6xl font-bold text-[#7877c6] font-['Orbitron']">{e.year}</div><div><h3 className="text-2xl font-bold text-white mb-3 font-['Exo_2']">{e.title}</h3><p className="text-gray-400 mb-4 font-['Inter']">{e.description}</p><div className="flex gap-2">{e.tags.map((tag, j) => (<span key={j} className="px-3 py-1 rounded-full bg-[#7877c6]/10 text-[#7877c6] text-sm font-['Inter']">{tag}</span>))}</div></div><div className="hidden md:block aspect-video rounded-xl bg-gray-800" /></motion.div>))}</div></div></section>
      <section className="py-24 bg-gray-900/50"><div className="container mx-auto px-6 lg:px-8"><h2 className="text-3xl font-bold text-white mb-12 text-center font-['Orbitron']">Recognition</h2><div className="grid grid-cols-3 md:grid-cols-6 gap-8">{["Cypress Partner", "Playwright Expert", "Selenium Pro", "k6 Advanced", "Postman", "JMeter"].map((name, i) => (<motion.div key={i} initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} className="flex flex-col items-center justify-center p-6 rounded-lg bg-gray-800/50 hover:bg-gray-800 transition-all"><Award className="w-8 h-8 text-[#7877c6] mb-2" /><span className="text-sm text-gray-400 text-center font-['Inter']">{name}</span></motion.div>))}</div></div></section>
      <section className="py-24 bg-black"><div className="container mx-auto px-6 lg:px-8"><h2 className="text-4xl font-bold text-white mb-16 text-center font-['Orbitron']">Pricing</h2><div className="max-w-md mx-auto"><div className="relative p-8 rounded-2xl border-2 border-[#7877c6] bg-gray-900/50"><div className="absolute -top-4 left-1/2 transform -translate-x-1/2"><span className="px-4 py-2 bg-gradient-to-r from-[#7877c6] to-[#a78bfa] text-white text-sm font-bold rounded-full">Most Popular</span></div><h3 className="text-2xl font-bold text-white mb-2 font-['Exo_2']">QA Pro</h3><div className="mb-4"><span className="text-4xl font-bold text-[#7877c6] font-['Orbitron']">$69/mo</span></div><p className="text-gray-400 mb-6 font-['Inter']">Complete test automation</p><ul className="space-y-3 mb-8">{["E2E automation", "API testing", "Performance tests", "CI/CD integration", "Reporting", "Support"].map((f, i) => (<li key={i} className="flex items-center gap-3"><CheckCircle className="w-5 h-5 text-[#7877c6]" /><span className="text-gray-300 font-['Inter']">{f}</span></li>))}</ul><a href="/contact" className="w-full inline-flex items-center justify-center px-6 py-3 rounded-lg font-semibold bg-gradient-to-r from-[#7877c6] to-[#a78bfa] text-white hover:from-[#a78bfa] hover:to-[#7877c6] transition-all font-['Inter']">Get started<ArrowRight className="ml-2 w-4 h-4" /></a></div></div></div></section>
      <section className="py-24 bg-gray-900/50"><div className="container mx-auto px-6 lg:px-8"><h2 className="text-4xl font-bold text-white mb-16 text-center font-['Orbitron']">FAQs</h2><div className="max-w-3xl mx-auto space-y-4">{[{ q: "Handle flaky tests?", a: "Isolation, retries, improved selectors." }, { q: "Device labs?", a: "Yes, BrowserStack and Firebase." }, { q: "CI/CD integration?", a: "Support all major platforms." }].map((faq, i) => (<details key={i} className="group"><summary className="flex items-center justify-between p-6 bg-gray-800 rounded-lg cursor-pointer hover:bg-gray-700 transition-colors font-['Exo_2'] font-bold text-white">{faq.q}<span className="text-[#7877c6]">+</span></summary><div className="p-6 text-gray-400 font-['Inter']">{faq.a}</div></details>))}</div></div></section>
      <section className="py-24 bg-black"><div className="container mx-auto px-6 lg:px-8"><div className="grid lg:grid-cols-2 gap-12"><div><h2 className="text-4xl font-bold text-white mb-6 font-['Orbitron']">Contact</h2><p className="text-lg text-gray-400 mb-8 font-['Inter']">Get testing assessment</p><div className="space-y-6">{[{ icon: Mail, label: "Email", value: "qa@linkinnovations.com" }, { icon: Phone, label: "Phone", value: "+1 (555) 123-4567" }, { icon: MapPin, label: "Location", value: "San Francisco" }].map((c, i) => (<div key={i} className="flex items-center gap-4"><div className="w-12 h-12 rounded-lg bg-gradient-to-br from-[#7877c6]/20 to-[#a78bfa]/20 flex items-center justify-center">{React.createElement(c.icon, { className: "w-6 h-6 text-[#7877c6]" })}</div><div><p className="text-white font-semibold font-['Inter']">{c.label}</p><p className="text-gray-400 font-['Inter']">{c.value}</p></div></div>))}</div></div><div className="bg-gray-800/50 p-8 rounded-2xl border border-gray-700"><form className="space-y-6"><div className="grid md:grid-cols-2 gap-6"><div><label className="block text-sm text-gray-300 mb-2 font-['Inter']">Name *</label><input type="text" required className="w-full px-4 py-3 bg-gray-700 border border-gray-600 rounded-lg text-white focus:ring-2 focus:ring-[#7877c6] font-['Inter']" placeholder="Your name" /></div><div><label className="block text-sm text-gray-300 mb-2 font-['Inter']">Email *</label><input type="email" required className="w-full px-4 py-3 bg-gray-700 border border-gray-600 rounded-lg text-white focus:ring-2 focus:ring-[#7877c6] font-['Inter']" placeholder="your@email.com" /></div></div><div><label className="block text-sm text-gray-300 mb-2 font-['Inter']">Company</label><input type="text" className="w-full px-4 py-3 bg-gray-700 border border-gray-600 rounded-lg text-white focus:ring-2 focus:ring-[#7877c6] font-['Inter']" placeholder="Company" /></div><div><label className="block text-sm text-gray-300 mb-2 font-['Inter']">Message *</label><textarea required rows={4} className="w-full px-4 py-3 bg-gray-700 border border-gray-600 rounded-lg text-white focus:ring-2 focus:ring-[#7877c6] font-['Inter'] resize-none" placeholder="Testing needs..." /></div><button type="submit" className="w-full inline-flex items-center justify-center px-6 py-3 bg-gradient-to-r from-[#7877c6] to-[#a78bfa] text-white font-semibold rounded-lg hover:from-[#a78bfa] hover:to-[#7877c6] transition-all font-['Inter']">Send<Send className="ml-2 w-4 h-4" /></button></form></div></div></div></section>
      <section className="py-24 bg-gray-900/50"><div className="container mx-auto px-6 lg:px-8 text-center"><h2 className="text-4xl font-bold text-white mb-6 font-['Orbitron']">Ready to accelerate testing?</h2><p className="text-xl text-gray-400 mb-10 font-['Inter']">Transform your QA process</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><a href="/contact" className="inline-flex items-center justify-center px-8 py-4 bg-gradient-to-r from-[#7877c6] to-[#a78bfa] text-white font-semibold rounded-lg hover:from-[#a78bfa] hover:to-[#7877c6] transition-all font-['Inter']">Get assessment<ArrowRight className="ml-2 w-5 h-5" /></a><a href="/case-studies" className="inline-flex items-center justify-center px-8 py-4 border-2 border-gray-600 text-gray-300 font-semibold rounded-lg hover:border-[#7877c6] transition-all font-['Inter']">View cases</a></div></div></section>
      <Footer />
    </div>
  );
}